[build]
  command = "npx prisma generate --schema=packages/database/prisma/schema.prisma && npx turbo run build --filter=@postador/web"
  publish = "apps/web/.next"

[build.environment]
  NEXT_PRIVATE_STANDALONE = "true"
